name: wellth
description: "Wellth App, Heath Care Services Platform"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^3.0.3

  # Routing
  go_router: ^17.0.0

  # HTTP client
  dio: ^5.9.0

  # Secure storage
  flutter_secure_storage: ^9.2.4

  # Simple key-value storage
  shared_preferences: ^2.5.3

  # Device info
  device_info_plus: ^12.2.0
  package_info_plus: ^9.0.0

  # Google Sign In
  google_sign_in: ^7.2.0

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  cached_network_image: ^3.4.1

  # Utilities
  uuid: ^4.5.2
  logger: ^2.6.2
  json_annotation: ^4.9.0

  # >> flutter pub run build_runner build
  # >> flutter pub run build_runner watch
  freezed_annotation: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  freezed: ^3.2.3
  json_serializable: ^6.11.2

flutter:
  uses-material-design: true

# >> flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/icons/app_icon_foreground.png"
  adaptive_icon_background: "#005F8D"
  adaptive_icon_foreground: "lib/assets/icons/app_icon_min.png"

# >> flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#005F8D"
  image: "lib/assets/icons/app_icon_small.png"
  # Android specific
  android: true
  android_12:
    color: "#005F8D"
    image: "lib/assets/icons/app_icon_small.png"
  # iOS specific
  ios: true
  fullscreen: true