name: wellth
description: "Wellth App, Heath Care Services Platform"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.5.0

  # Routing
  go_router: ^14.0.0

  # HTTP client
  dio: ^5.7.0

  # Secure storage
  flutter_secure_storage: ^9.2.2

  # Simple key-value storage
  shared_preferences: ^2.3.3

  # Device info
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0

  # Google Sign In
  google_sign_in: ^6.1.5

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_launcher_icons: ^0.13.1

  # Utilities
  uuid: ^4.5.1
  logger: ^2.0.2+1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

# >>flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/icons/app_icon_foreground.png"
  adaptive_icon_background: "#005F8D"
  adaptive_icon_foreground: "lib/assets/icons/app_icon_min.png"
